#!/usr/bin/env bash
# This script will display the contents of the passwd file
# Open the file for reading
file=/etc/passwd
while IFS=':' read -r username uid shell; do
	  # Print the username, UID, and shell
	    echo "$username $uid $shell"
    done < "$file"
