#!/usr/bin/env bash
# This script tells a story using the passwd file!
file=/etc/passwd
IFS=':'
while read -r username password uid gid gecos home shell; do
	    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $gecos"
    done < "$file"
    
