#!/usr/bin/env bash
# This script also prints Best School 10 times, but using a while statement
counter=1
while [ $counter -lt 10 ]
do
if [ $counter -eq 9 ]
	then
	echo "Hi"
fi
	echo "Best School"
((counter++))
done
