#!/usr/bin/env bash
# This script also prints Best School 10 times, but using a while statement
counter=1
while [ $counter -lt 10 ]
do
if [ $counter -eq 4 ]
	then
	echo "bad luck"
elif [ $counter -eq 8 ]
then
	echo "good luck"
else
	echo "Best School"
fi
	((counter++))
done
